<section class="page_slide" id="mentions_legales">
	
	<div class="center part">
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">Editeur</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Le site&nbsp;</span><a href="http://www.edelis.immo"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif';">www.edelis.immo</span></a><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;est la propri&eacute;t&eacute; d'Edelis. Le Directeur de la publication est Sylvère HAMEL, en qualité de Directeur Général de la société EDELIS.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">Cr&eacute;dit photo</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Patrick Raffin, © Ecliptique / Laurent Thion </span><a href="http://www.patrick-raffin.book.fr"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif';">www.patrick-raffin.book.fr</span></a><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;"></span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">Cr&eacute;dit Image</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Fotolia, Adobe Stock, Istock, Guetty image</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">H&eacute;bergement</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Le site&nbsp;</span><a href="http://www.edelis.immo"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif';">www.edelis.immo</span></a><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;est h&eacute;berg&eacute; sur des mat&eacute;riels informatiques appartenant &agrave; EDELIS, lesquels sont h&eacute;berg&eacute;s et administr&eacute;s par la soci&eacute;t&eacute; OVH - Siège social : 2 rue Kellermann 59100 Roubaix - France.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">R&eacute;alisation du site</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">La r&eacute;alisation du site&nbsp;</span><a href="http://www.edelis.immo"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif';">www.edelis.immo</span></a><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;a &eacute;t&eacute; confi&eacute;e, sous la direction de la soci&eacute;t&eacute; EDELIS, &agrave; l&rsquo;agence digitale pour l&rsquo;immobilier MKI ; tous les droits y aff&eacute;rents &eacute;tant c&eacute;d&eacute;s au Groupe GCC.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">Donn&eacute;es personnelles</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">D&eacute;claration CNIL</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">En conformit&eacute; avec les dispositions de la loi du 6 janvier 1978 modifi&eacute;e par la loi du 6 ao&ucirc;t 2004, les traitements de donn&eacute;es personnelles mis en &oelig;uvre dans le cadre du site&nbsp;www.edelis.immo ont fait l'objet de d&eacute;claration aupr&egrave;s de la Commission Nationale de l'Informatique et des Libert&eacute;s (CNIL) N&deg;&nbsp;1588428&nbsp;en date du 22 mai 2012.</span></li>
		</ul>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">L'utilisateur est inform&eacute; qu'il dispose d'un droit d'acc&egrave;s, d&rsquo;opposition, de rectification et de suppression portant sur les donn&eacute;es le concernant, en envoyant un courrier &eacute;lectronique &agrave; l&rsquo;adresse suivante :&nbsp;</span><a href="mailto:donnees@edelis.com"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">donnees@edelis.fr</span></a></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">Collecte et utilisation des donn&eacute;es</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">Responsable du traitement</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">EDELIS est le responsable du traitement en ce qui concerne les donn&eacute;es personnelles qui lui sont fournies.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">Collecte et utilisation des donn&eacute;es</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Les informations recueillies &agrave; partir du site ou communiqu&eacute;es par l&rsquo;utilisateur, notamment du fait des formulaires pr&eacute;sents sur le site, ou par le biais de service tel que le chat en ligne, sont destin&eacute;es &agrave; la soci&eacute;t&eacute; EDELIS. Elles sont enregistr&eacute;es dans un fichier informatique, et sont obligatoires pour le traitement de votre demande, un d&eacute;faut de r&eacute;ponse pouvant entrainer l&rsquo;incapacit&eacute; de traiter celle-ci. Elles ne seront utilis&eacute;es que pour les seules finalit&eacute;s de l'objet de la collecte et, le cas &eacute;ch&eacute;ant, pour toute op&eacute;ration de prospection commerciale. Elles peuvent &eacute;galement &ecirc;tre communiqu&eacute;es aux autres soci&eacute;t&eacute;s appartenant et/ou affili&eacute;es au Groupe GCC, ainsi qu&rsquo;&agrave; des tiers (partenaires, mandataires, prestataires, sous-traitants) qui sont amen&eacute;s &agrave; intervenir dans les traitements. EDELIS ne recueille que les informations n&eacute;cessaires &agrave; leur traitement et les conserve pendant la dur&eacute;e n&eacute;cessaire &agrave; l&rsquo;accomplissement de ces finalit&eacute;s. <br/>
		EDELIS met en &oelig;uvre tous les moyens destin&eacute;s &agrave; assurer la s&eacute;curit&eacute; et la confidentialit&eacute; des fichiers constitu&eacute;s &agrave; partir des donn&eacute;es personnelles collect&eacute;es sur le site. Cependant, EDELIS ne ma&icirc;trise pas le fonctionnement de l'internet et attire l'attention des utilisateurs sur l'existence d'&eacute;ventuels risques en termes de confidentialit&eacute; des donn&eacute;es transitant via ce r&eacute;seau.</span></p>
		<p style="margin-bottom: .0001pt; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">Adresses &eacute;lectroniques (E-mail)</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Si l'utilisateur communique &agrave; EDELIS son adresse &eacute;lectronique, cette derni&egrave;re communiquera avec lui par e-mail. Cette adresse ne sera pas communiqu&eacute;e &agrave; des tiers ne faisant pas partie d&rsquo;EDELIS, &agrave; l&rsquo;exception des tiers concern&eacute;s.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">N&eacute;anmoins, sous r&eacute;serve de l&rsquo;accord de l&rsquo;utilisateur, la soci&eacute;t&eacute; EDELIS &nbsp;pourra &ecirc;tre amen&eacute;e &agrave; transmettre son adresse e-mail aux autres soci&eacute;t&eacute;s appartenant et/ou affili&eacute;es au Groupe GCC, ainsi qu&rsquo;&agrave; ses partenaires, afin de lui faire parvenir des offres commerciales susceptibles de l&rsquo;int&eacute;resser. L&rsquo;utilisateur pourra se d&eacute;sinscrire &agrave; tout moment des listes de prospection soit en suivant le lien de d&eacute;sinscription pr&eacute;sent dans chacune des lettres d&rsquo;information et dans chaque envoi d&rsquo;offres promotionnelles, soit en adressant sa demande &agrave;&nbsp;</span><a href="mailto:donnees@edelis.com"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">donnees@edelis.com</span></a><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">Cookies et Statistiques</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">EDELIS utilise des cookies pour analyser l&rsquo;utilisation du site et am&eacute;liorer sa fr&eacute;quentation. EDELIS peut donc suivre l&rsquo;utilisation du site par chaque utilisateur. Les cookies permettent &eacute;galement de mieux analyser les configurations de trafic du site. EDELIS&nbsp;ne suit pas le parcours des utilisateurs &agrave; l'ext&eacute;rieur du site. L'utilisateur est inform&eacute; de ce que les tiers qui int&egrave;grent des annonces ou des informations peuvent &eacute;galement utiliser leurs propres cookies.&nbsp;</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">L'utilisateur autorise EDELIS&nbsp;&agrave; utiliser son adresse IP pour diagnostiquer les incidents au niveau de son serveur, pour administrer son site ou pour rassembler des informations d&eacute;mographiques g&eacute;n&eacute;rales.&nbsp;</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">EDELIS utilise &eacute;galement des cookies destin&eacute;s &agrave; faciliter la navigation sur le site et la fourniture du service en ligne, tels que les cookies de type &laquo;&nbsp;session utilisateur&nbsp;&raquo;.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">L&rsquo;utilisateur reconna&icirc;t avoir &eacute;t&eacute; inform&eacute; de ces cookies et autorise EDELIS&nbsp;&agrave; les utiliser. Toutefois, il pourra, s&rsquo;il le souhaite, s&rsquo;opposer &agrave; l&rsquo;enregistrement de ces cookies en configurant le navigateur install&eacute; sur son syst&egrave;me, pour &ecirc;tre averti de l&rsquo;arriv&eacute;e d&rsquo;un cookie et pour pouvoir le refuser.<br /> N&eacute;anmoins, le refus des cookies peut emp&ecirc;cher l&rsquo;acc&egrave;s et l&rsquo;utilisation du site et des services.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Modifiez vos pr&eacute;f&eacute;rences de cookies en cliquant le lien suivant : <a href="javascript:openAxeptioCookies()"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">Gestion des cookies</span></a></span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">&nbsp;</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">Propri&eacute;t&eacute; intellectuelle et utilisation des documents</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">Propri&eacute;t&eacute; intellectuelle</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">L&rsquo;ensemble de ce Site (structure, pr&eacute;sentation et contenu) constitue une &oelig;uvre prot&eacute;g&eacute;e par la l&eacute;gislation fran&ccedil;aise et internationale en vigueur sur le droit d&rsquo;auteur et, d&rsquo;une mani&egrave;re g&eacute;n&eacute;rale, sur la propri&eacute;t&eacute; intellectuelle.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Toutes les informations ou documents contenus dans le Site, ainsi que tous les &eacute;l&eacute;ments cr&eacute;&eacute;s pour le Site notamment les textes, donn&eacute;es, dessins, graphiques, photos, animations, sons, vid&eacute;os, y compris les documents t&eacute;l&eacute;chargeables sont, soit la propri&eacute;t&eacute; d&rsquo;EDELIS, soit font l'objet d'un droit d'exploitation. Ces &eacute;l&eacute;ments sont soumis &agrave; la l&eacute;gislation prot&eacute;geant le droit d'auteur. Par cons&eacute;quent, aucune licence, ni aucun autre droit sauf celui de consulter les informations, n'est conf&eacute;r&eacute; &agrave; quiconque au regard des droits de la propri&eacute;t&eacute; intellectuelle.</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">Principe d&rsquo;interdiction et autorisations sp&eacute;ciales</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">L'Utilisateur s'interdit de reproduire, repr&eacute;senter, modifier, publier, transmettre, d&eacute;naturer ou exploiter, m&ecirc;me pour un but gratuit, quel qu'il soit, tout ou partie du Site ou de son contenu, par quelque proc&eacute;d&eacute; et sur quelque support que ce soit. En particulier, il s'interdit la cr&eacute;ation de tout lien vers un ou plusieurs services.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Toute exploitation non autoris&eacute;e du Site ou de son contenu, des informations qui y sont divulgu&eacute;es engagerait la responsabilit&eacute; de l'Utilisateur et constituerait une contrefa&ccedil;on sanctionn&eacute;e par les articles L 335-2 et suivants du Code de la propri&eacute;t&eacute; intellectuelle.</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">&nbsp;</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">Limites de garantie et de responsabilit&eacute;</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">Liens</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Le Site permet l'acc&egrave;s &agrave; des sites de tiers par le biais de liens. Dans la mesure o&ugrave; EDELIS&nbsp;n'a pas le contr&ocirc;le de ces sites, cette derni&egrave;re ne peut en aucun cas ni garantir ni &ecirc;tre responsable notamment de la disponibilit&eacute; des dits sites, des contenus ou autres &eacute;l&eacute;ments se trouvant sur ces sites ou des transactions que pourrait effectuer l&rsquo;Utilisateur sur ces sites tiers. EDELIS&nbsp;recommande aux Utilisateurs de consulter les informations l&eacute;gales et conditions d&rsquo;utilisation des sites concern&eacute;s. Toute cr&eacute;ation de liens vers le Site est soumise &agrave; l&rsquo;autorisation pr&eacute;alable et expresse d&rsquo;EDELIS qui pourra &ecirc;tre r&eacute;voqu&eacute;e &agrave; tout moment &agrave; sa seule discr&eacute;tion. EDELIS se r&eacute;serve le droit de demander la suppression de tout lien vers le Site qui n'aurait pas &eacute;t&eacute;, ou ne serait plus, autoris&eacute;.</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">&nbsp;</span></p>
		<p style="text-align: justify; line-height: normal; background: white; margin: 6.0pt 0cm 6.0pt 0cm;"><span style="font-size: 13.0pt; font-family: 'Verdana','sans-serif'; color: #645d53;">Limites de garantie et de responsabilit&eacute;</span></p>
		<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">EDELIS d&eacute;cline toute garantie ou responsabilit&eacute; quant aux informations et outils disponibles sur le Site. Les informations fournies sur le Site et les r&eacute;sultats des simulations r&eacute;alis&eacute;es &agrave; partir des outils disponibles sur le Site le sont &agrave; titre purement indicatif. Ils ne sauraient dispenser l&rsquo;utilisateur d&rsquo;une analyse compl&eacute;mentaire et adapt&eacute;e &agrave; sa situation personnelle.</span></p>
		<p style="margin-bottom: 12.0pt; text-align: justify; line-height: normal; background: white;"><span style="font-size: 15.0pt; font-family: 'Verdana','sans-serif'; color: #2b4556;">&nbsp;</span></p>
		<p>&nbsp;</p>
<p style="margin-bottom: .0001pt; text-align: justify; line-height: 14.25pt; background: white;"><span style="font-size: 9.0pt; font-family: 'Verdana','sans-serif'; color: black;">Pour l’année 2019, l’index égalité Hommes-Femmes est de 71/100.
Notre entreprise est très engagée dans ce domaine et va renforcer ses actions.</p>
	</div>
	
</section>